### ISSUE TITLE
Tracking against feature list

### ISSUE THREAD

**Issue by lyzadanger** [cloudfour/fabricator#2]
This is a copy of the feature list from `drizzle` so I can keep it in mind:

This is my initial sweep of project requirements, we can modify as needed.
- [x] Template organization
  - [x] Multi-level hierarchy ("Patterns," "Pages," "Sandbox" vs "Elements," "Components," "Utilities," etc.)
  - [x] Explicit ordering of templates
  - [x] Implicit ordering of templates (alphabetical, always following explicitly ordered templates)
  - [x] "hidden" templates that only function as partials
- [x] Template compilation (Handlebars or possibly agnostic)
  - [x] HTML beautification of exported templates
- [x] Ability to include other templates as partials
- [x] Ability to define and use custom template helpers
- [x] Ability to define properties of a template using YAML front-matter
- [x] Default template title derived from filename (`01-hello-world` → `Hello World`)
- [x] Ability to store data in YAML or JSON files that can be easily referenced from templates
- [x] UI for navigating templates
  - [x] Ability to define the project name
  - [x] Templating (separated from project templates, can use Handlebars or something else if more appropriate)
  - [x] Partials (for including nav, etc. across style guide, for example)
  - [x] Ability to output the project name in a template (such as in the `<title>`)
  - [x] Ability to output the most recent build date/time
  - [x] Ability to iterate over project templates (patterns, pages, etc.)
  - [x] Ability to output project template content (YAML front-matter, compiled content, etc.)
  - [x] Ability to output code for template content (`<pre><code>{{{escaped}}}</code></pre>` or whatever) with language-appropriate syntax highlighting
  - [x] Ability to vary templates for certain groups (for example, a style guide interface for "Patterns," a straightforward index for "Pages")
  - [x] PostCSS (for styling this UI)
    - [x] custom media queries
    - [x] variables
    - [x] calc
    - [x] autoprefixer
  - [x] Ability to define "Welcome" content for index (depending on how we handle template organization and UI stuff, we might get this for free)
- [ ] Project-specific assets (should be relatively unopinionated, maybe even easy to change directory names, etc. in the future?)
  - [ ] styles
  - [ ] images
  - [ ] javascript
  - [ ] possibly just files/whatever/etc?
- [x] Ability to build project (duh)
- [x] Livereload (I :heart: [BrowserSync](http://www.browsersync.io/), but y'all already know that)
- [x] JavaScript module loading (for patterns and third-party stuff)
- [x] ES6 JavaScript syntax support
- [x] Minification/concatenation support for exporting for production
- [ ] Sane `.editorconfig`, etc. to enforce project-level conventions

**Comment by lyzadanger** [comment]
Regarding partials: there are a few mechanisms.
- Anything under materials is registered as a partial, as the filename sans extension, e.g. `button`
- Anything under an includes directory (at `src/views/layouts/includes`) is registered as a partial. This is meant for partials for the UI of the pattern library itself
- There is a special helper, `material` that can be used to manage context and stuff, e.g. `{{ material name context }}`

This model is a step backward for namespace collisions (it seems we have to make sure all files have a unique name) but otherwise gives various options.

**Comment by tylersticka** [comment]
Removed examples from explicit ordering and "hidden" patterns/partials, as I now think that could be handled via YAML (features were too overt in suggesting a solution).

**Comment by erikjung** [comment]
Should we just create issues to implement chunks of this feature set?

**Comment by lyzadanger** [comment]
@erikjung Why don't we keep this as a central list but start calving off things into separate issues (I already started doing that vis-a-vis ordering, e.g.)? Does that seem plausible?

**Comment by erikjung** [comment]
@lyzadanger Yes, that's what I was imagining.

Also, I checked off a few more boxes that are inherently complete.

**Comment by lyzadanger** [comment]
On

|  Ability to define the project name

You can indirectly do this by changing the `title` front-matter attribute in templates. Default  for `index.html` is "Overview | Fabricator" but can easily be changed to project name.

Does that suffice?

**Comment by lyzadanger** [comment]
| Ability to output the most recent build date/time

Should be straightforward with a helper that can use `moment.js`.

**Comment by lyzadanger** [comment]
@tylersticka Having trouble understanding this requirement:

| Ability to output project template content (YAML front-matter, compiled content, etc.)

Can you shed some light?

**Comment by tylersticka** [comment]
> On
> 
> | Ability to define the project name
> 
> You can indirectly do this by changing the title front-matter attribute in templates. Default for index.html is "Overview | Fabricator" but can easily be changed to project name.
> 
> Does that suffice?

It does, I think!

> @tylersticka Having trouble understanding this requirement:
> 
> | Ability to output project template content (YAML front-matter, compiled content, etc.)
> 
> Can you shed some light?

You should be able to set some YAML in a pattern (example, `foo: bar`) and then from the styleguide reference it, so `{{foo}}` outputs `bar`. This probably made more sense as a spelled-out requirement when we were rolling our own solution.

**Comment by erikjung** [comment]
> Ability to output project template content (YAML front-matter, compiled content, etc.)

I think this already exists inherently.
